export declare enum RoleType {
    SUPER_ADMIN = "SUPER_ADMIN",
    ADMIN = "ADMIN",
    OWNER = "OWNER",
    EMPLOYEE = "EMPLOYEE"
}
export declare enum PermissionType {
    USER_CREATE = "user.create",
    USER_READ = "user.read",
    USER_UPDATE = "user.update",
    USER_DELETE = "user.delete",
    SHOP_CREATE = "shop.create",
    SHOP_READ = "shop.read",
    SHOP_UPDATE = "shop.update",
    SHOP_DELETE = "shop.delete",
    PRODUCT_CREATE = "product.create",
    PRODUCT_READ = "product.read",
    PRODUCT_UPDATE = "product.update",
    PRODUCT_DELETE = "product.delete",
    INVENTORY_STOCK_IN = "inventory.stock_in",
    INVENTORY_STOCK_OUT = "inventory.stock_out",
    INVENTORY_READ = "inventory.read",
    INVENTORY_TRANSACTION_READ = "inventory.transaction.read",
    MENU_CREATE = "menu.create",
    MENU_READ = "menu.read",
    MENU_UPDATE = "menu.update",
    MENU_DELETE = "menu.delete",
    ORDER_CREATE = "order.create",
    ORDER_READ = "order.read",
    ORDER_UPDATE_STATUS = "order.update_status",
    ORDER_CANCEL = "order.cancel",
    TASK_CREATE = "task.create",
    TASK_READ = "task.read",
    TASK_UPDATE = "task.update",
    DEVICE_CREATE = "device.create",
    DEVICE_READ = "device.read",
    DEVICE_UPDATE = "device.update",
    SUBSCRIPTION_MANAGE = "subscription.manage",
    REPORT_READ_ALL = "report.read_all",
    REPORT_READ_SHOP = "report.read_shop",
    SETTING_MANAGE = "setting.manage",
    PERMISSION_MANAGE = "permission.manage"
}
export declare const RolePermissions: Record<RoleType, PermissionType[]>;
