export enum RoleType {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  OWNER = 'OWNER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum PermissionType {
  USER_CREATE = 'user.create',
  USER_READ = 'user.read',
  USER_UPDATE = 'user.update',
  USER_DELETE = 'user.delete',

  SHOP_CREATE = 'shop.create',
  SHOP_READ = 'shop.read',
  SHOP_UPDATE = 'shop.update',
  SHOP_DELETE = 'shop.delete',

  PRODUCT_CREATE = 'product.create',
  PRODUCT_READ = 'product.read',
  PRODUCT_UPDATE = 'product.update',
  PRODUCT_DELETE = 'product.delete',

  INVENTORY_STOCK_IN = 'inventory.stock_in',
  INVENTORY_STOCK_OUT = 'inventory.stock_out',
  INVENTORY_READ = 'inventory.read',
  INVENTORY_TRANSACTION_READ = 'inventory.transaction.read',

  MENU_CREATE = 'menu.create',
  MENU_READ = 'menu.read',
  MENU_UPDATE = 'menu.update',
  MENU_DELETE = 'menu.delete',

  ORDER_CREATE = 'order.create',
  ORDER_READ = 'order.read',
  ORDER_UPDATE_STATUS = 'order.update_status',

  TASK_CREATE = 'task.create',
  TASK_READ = 'task.read',
  TASK_UPDATE = 'task.update',

  SUBSCRIPTION_MANAGE = 'subscription.manage',
  REPORT_READ_ALL = 'report.read_all',
  REPORT_READ_SHOP = 'report.read_shop',
  SETTING_MANAGE = 'setting.manage',
  PERMISSION_MANAGE = 'permission.manage',
}

export const RolePermissions: Record<RoleType, PermissionType[]> = {
  [RoleType.SUPER_ADMIN]: Object.values(PermissionType),
  [RoleType.ADMIN]: [
    PermissionType.USER_CREATE,
    PermissionType.USER_READ,
    PermissionType.USER_UPDATE,
    PermissionType.SHOP_CREATE,
    PermissionType.SHOP_READ,
    PermissionType.SHOP_UPDATE,
    PermissionType.PRODUCT_CREATE,
    PermissionType.PRODUCT_READ,
    PermissionType.PRODUCT_UPDATE,
    PermissionType.PRODUCT_DELETE,
    PermissionType.INVENTORY_STOCK_IN,
    PermissionType.INVENTORY_STOCK_OUT,
    PermissionType.INVENTORY_READ,
    PermissionType.INVENTORY_TRANSACTION_READ,
    PermissionType.MENU_CREATE,
    PermissionType.MENU_READ,
    PermissionType.MENU_UPDATE,
    PermissionType.MENU_DELETE,
    PermissionType.ORDER_READ,
    PermissionType.REPORT_READ_SHOP,
    PermissionType.PERMISSION_MANAGE,
  ],
  [RoleType.OWNER]: [
    PermissionType.USER_CREATE,
    PermissionType.USER_READ,
    PermissionType.USER_UPDATE,
    PermissionType.SHOP_READ,
    PermissionType.PRODUCT_CREATE,
    PermissionType.PRODUCT_READ,
    PermissionType.PRODUCT_UPDATE,
    PermissionType.PRODUCT_DELETE,
    PermissionType.INVENTORY_STOCK_IN,
    PermissionType.INVENTORY_STOCK_OUT,
    PermissionType.INVENTORY_READ,
    PermissionType.INVENTORY_TRANSACTION_READ,
    PermissionType.MENU_CREATE,
    PermissionType.MENU_READ,
    PermissionType.MENU_UPDATE,
    PermissionType.MENU_DELETE,
    PermissionType.ORDER_CREATE,
    PermissionType.ORDER_READ,
    PermissionType.ORDER_UPDATE_STATUS,
    PermissionType.TASK_CREATE,
    PermissionType.TASK_READ,
    PermissionType.TASK_UPDATE,
    PermissionType.REPORT_READ_SHOP,
  ],
  [RoleType.EMPLOYEE]: [
    PermissionType.PRODUCT_READ,
    PermissionType.INVENTORY_READ,
    PermissionType.INVENTORY_STOCK_IN,
    PermissionType.INVENTORY_STOCK_OUT,
    PermissionType.MENU_READ,
    PermissionType.ORDER_CREATE,
    PermissionType.ORDER_READ,
    PermissionType.ORDER_UPDATE_STATUS,
    PermissionType.TASK_READ,
    PermissionType.TASK_UPDATE,
  ],
};
