export enum RoleType {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  OWNER = 'OWNER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum PermissionType {
  MANAGE_ALL_SHOPS = 'MANAGE_ALL_SHOPS',
  MANAGE_SUBSCRIPTIONS = 'MANAGE_SUBSCRIPTIONS',
  MANAGE_ADMINS = 'MANAGE_ADMINS',
  VIEW_ALL_REPORTS = 'VIEW_ALL_REPORTS',
  MANAGE_SYSTEM_SETTINGS = 'MANAGE_SYSTEM_SETTINGS',

  MANAGE_MULTIPLE_SHOPS = 'MANAGE_MULTIPLE_SHOPS',
  CREATE_OWNERS = 'CREATE_OWNERS',
  VIEW_SHOP_REPORTS = 'VIEW_SHOP_REPORTS',
  MANAGE_PERMISSIONS = 'MANAGE_PERMISSIONS',

  MANAGE_EMPLOYEES = 'MANAGE_EMPLOYEES',
  MANAGE_PRODUCTS = 'MANAGE_PRODUCTS',
  MANAGE_INVENTORY = 'MANAGE_INVENTORY',
  MANAGE_ORDERS = 'MANAGE_ORDERS',
  VIEW_BUSINESS_REPORTS = 'VIEW_BUSINESS_REPORTS',

  TAKE_ORDERS = 'TAKE_ORDERS',
  UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS',
  MANAGE_STOCK = 'MANAGE_STOCK',
  VIEW_ASSIGNED_TASKS = 'VIEW_ASSIGNED_TASKS',
}

export const RolePermissions: Record<RoleType, PermissionType[]> = {
  [RoleType.SUPER_ADMIN]: [
    PermissionType.MANAGE_ALL_SHOPS,
    PermissionType.MANAGE_SUBSCRIPTIONS,
    PermissionType.MANAGE_ADMINS,
    PermissionType.VIEW_ALL_REPORTS,
    PermissionType.MANAGE_SYSTEM_SETTINGS,
  ],
  [RoleType.ADMIN]: [
    PermissionType.MANAGE_MULTIPLE_SHOPS,
    PermissionType.CREATE_OWNERS,
    PermissionType.VIEW_SHOP_REPORTS,
    PermissionType.MANAGE_PERMISSIONS,
  ],
  [RoleType.OWNER]: [
    PermissionType.MANAGE_EMPLOYEES,
    PermissionType.MANAGE_PRODUCTS,
    PermissionType.MANAGE_INVENTORY,
    PermissionType.MANAGE_ORDERS,
    PermissionType.VIEW_BUSINESS_REPORTS,
  ],
  [RoleType.EMPLOYEE]: [
    PermissionType.TAKE_ORDERS,
    PermissionType.UPDATE_ORDER_STATUS,
    PermissionType.MANAGE_STOCK,
    PermissionType.VIEW_ASSIGNED_TASKS,
  ],
};
